### ISSUE TITLE
Context Quickie Eclipse Preference doesn't apply

### ISSUE THREAD

**Issue by SBM1952** [ContextQuickie/ContextQuickie#1]
Hi, i have followed your tutorial and the add-on doesn't appear.
When i try to enable the add-on in  Eclipse preferences, it doesn't let me apply the changes. I've checked the location of the tortoise and its ok. 

Here you got the Screenshot
![capture](https://cloud.githubusercontent.com/assets/10478999/11295038/7e047e2a-8f68-11e5-8965-888c5d943e6e.PNG)

thanks in advance

**Comment by ContextQuickie** [comment]
It seems that eclipse cannot apply the settings if the path to the programs doesn't exist (even if the plugin is not enabled). Can you please try to copy the path to TortoiseProc.exe also to the path of Beyond Compare and Tortoise Git? The the apply button will be enabled.
I will check if it is possible to turn off validation if a feature is not enabled.

**Comment by Sugreev1981** [comment]
Hi, I applied your reccomendation and effectivly the add-on  works.
By the way, i'm having some issues trying to use the add-on from Eclipse Luna. It seems that theres is a date issue with tortoiseSVN within the add-on. Take a look at the resuming prompt 

![quickieprompts](https://cloud.githubusercontent.com/assets/10478999/11334709/245abe5e-91d7-11e5-9193-19936e1d25d7.png)



However with Eclipse Mars it works correctly.

**Comment by ContextQuickie** [comment]
Can you please provide additional information regarding this issue?
* Do you use the same version of ContextQuickie in Luna and Mars and which version is it?
* Which steps causes the issue or how can it be reproduced?

**Comment by ContextQuickie** [comment]
I will close this issue as it went away from the original topic. The second issue will be continued in #2
