### ISSUE TITLE
error on initially opened preferences

### ISSUE THREAD

**Issue by Bananeweizen** [ContextQuickie/ContextQuickie#10]
When opening the preference page, an error is shown. It goes away by just clicking once into the beyond compare path field without changing any values.
![2016-10-10_18h36_43](https://cloud.githubusercontent.com/assets/406876/19243604/80c497fc-8f18-11e6-869c-1e2a5d0b834e.png)

**Comment by ContextQuickie** [comment]
Hello,
which versions of Eclipse and ContextQuickie do you use? I tried to reproduce the problem with Eclipse Mars SR2 and ContextQuickie 0.6.2 but didn't get the error.

**Comment by Bananeweizen** [comment]
Neon.1 on Windows 7. ContextQuickie version as available on update site of yesterday (I'm not at the machine right now, where I had the bug).

**Comment by ContextQuickie** [comment]
Ok, do you have installed all of the tools (Tortoise SVN/Tortoise Git/Beyond Compare)?

**Comment by ContextQuickie** [comment]
I tried to fix this issue in version 0.6.3. Can you please have a look at it?
If you don't have any comments regarding this topic, you can close this issue.

**Comment by Bananeweizen** [comment]
Working fine now.
