### ISSUE TITLE
Add the blame command to the TortoiseGIT context menu

### ISSUE THREAD

**Issue by jorgediaz-lr** [ContextQuickie/ContextQuickie#12]
Blame command is not available for TortoiseGIT

In order to speed up Eclipse, I have removed internal git modules and I have replaced that commands with ContextQuickie.
The only command I am missing is blame, it is possible to add it?

Thank you!

**Comment by ContextQuickie** [comment]
Have a look at version 0.7.1, I added the blame command for TortoiseGit there.

**Comment by jorgediaz-lr** [comment]
Hi @ContextQuickie 

I have update the eclipse plugin and it works fine!

Thank a lot!!
