### ISSUE TITLE
Error when opening context menu in Eclipse 4.8

### ISSUE THREAD

**Issue by foxsilverfox** [ContextQuickie/ContextQuickie#15]
eclipse.buildId=4.8.0.I20180611-0500
java.version=1.8.0_74
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

org.eclipse.e4.ui.workbench
Error
Mon Jul 02 11:21:12 EDT 2018
Unable to generate the parameterized command with the id "ContextQuickie.commands.TortoiseHg.TortoiseHgCommand" with the {ContextQuickie.commands.TortoiseGit.TortoiseGitCommand.CommandID=commit, ContextQuickie.commands.TortoiseGit.TortoiseGitCommand.RequiresPath=true} parameter(s). Model details: ContextQuickie.commands.TortoiseHg.TortoiseHgCommand=org.eclipse.e4.ui.model.application.ui.menu.impl.HandledMenuItemImpl@4051059e (tags: null, contributorURI: null) (widget: null, renderer: org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer@3ea1729e, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (label: Hg Commit..., iconURI: platform:/plugin/ContextQuickie/icons/TortoiseGit/menucommit.png, tooltip: null, enabled: true, selected: false, type: Push) (mnemonics: null) (wbCommand: null)

**Comment by foxsilverfox** [comment]
Yes the issue has been fixed by version 0.8.2

Thank you for prompt response

**Comment by ContextQuickie** [comment]
Fixed in version 0.8.2
