### ISSUE TITLE
Eclipse Oomph setup task for checkout

### ISSUE THREAD

**Issue by OLibutzki** [ContextQuickie/ContextQuickie#16]
Hi,

as we are very unhappy with the Subclipse and Subversive we started using your plugin which is very helpful.

We set up our IDE by using the Eclipse Installer (Oomph). As we do not have Subclipse or Subversive it's not possible to trigger the checkout during the installation process.

We have a workaround of creating a launch configuration which triggers the svn command-line tool, but that's very inconvenient.

It would be cool, if you could provide an Oomph custom setup task for checkout.

Keep up the good work.

Kind regards
Oliver

**Comment by ContextQuickie** [comment]
Hello Oliver,
not sure if this is possible at the moment, there are some questions regarding this issue:
- Do you know if this could bread compatibility with older eclipse versions?
- What exactly do you expect to be executed? Should it execute Tortoise SVN client with the checkout command? If yes, should the dialog be closed afterwards. There are some options for closing Tortoise SVN dialogs:
/closeonend:0 don't close the dialog automatically 
/closeonend:1 auto close if no errors 
/closeonend:2 auto close if no errors and conflicts 
/closeonend:3 auto close if no errors, conflicts and merges 

Or should the action be configured in Oomph?

BR

**Comment by OLibutzki** [comment]
I do not think that this could break compatibility. You should not include the Oomph stuff in the same feature/iu as the other things.

The checkout diaog is a "problem" as I would like to setup Eclipse in an non-interactive way. As TortoiseProc is designed to interact with the user it might not be the best solution.

In my opinion it's better to fall back to command-line svn in this case.

**Comment by ContextQuickie** [comment]
Ok, so I can close this issue?
