### ISSUE TITLE
Add Refresh-Mechanism if possible

### ISSUE THREAD

**Issue by oilid** [ContextQuickie/ContextQuickie#17]
Hey,

thanks for the great plugin.
I only would like to ask for a refresh-mechanism in eclipse for example in the "project explorer" for the currently selected item. If you for example create a new file called "test.txt" in eclipse and then revert it by tortoisesvn, then the file will be deleted but it is still visible in the project explorer. Only a manual refresh will update the correct file/folder state.

Is it may possible to refresh the selected item in eclipse automatically after a tortoisesvn action?

Greetings
Oilid

**Comment by ContextQuickie** [comment]
Hello Oilid,
attached you'll find an update which should support refreshing. Can you please check if it is working as expected?
[ContextQuickie_0.8.3.201807071707.zip](https://github.com/ContextQuickie/ContextQuickie/files/2172857/ContextQuickie_0.8.3.201807071707.zip)

**Comment by oilid** [comment]
thanks a lot for your fast patch! It works but your implemented refresh mechanism blocks the whole UI for that moment.
Could you use the eclipse refresh mechanism which runs by default at the background?
This would be great and helps a lot :-)

Thanks again!

**Comment by ContextQuickie** [comment]
You're right, I called the wrong API for starting the thread waiting for the process to finish. Attached another update. Is it working better?
[ContextQuickie_0.8.3.201807091746.zip](https://github.com/ContextQuickie/ContextQuickie/files/2176961/ContextQuickie_0.8.3.201807091746.zip)

**Comment by oilid** [comment]
It works great now! No hang or crash issue anymore...
Thanks a lot :-)

Could you release it?

**Comment by ContextQuickie** [comment]
Done

**Comment by oilid** [comment]
Hey,

the current version installed from http://contextquickie.github.io/ContextQuickie/ references to a version 0.8.3.201807071707 which contains the old thread blocking behaviour :-/

Could you update it to the new version please?

**Comment by ContextQuickie** [comment]
You're right, I updated the binaries in the update site. Sorry for the inconvenience caused
