### ISSUE TITLE
Error message when using Tortoise SVN with Eclipse Luna

### ISSUE THREAD

**Issue by ContextQuickie** [ContextQuickie/ContextQuickie#2]
@SBM1952 wrote in #1
> Hi, I applied your reccomendation and effectivly the add-on works.
> By the way, i'm having some issues trying to use the add-on from Eclipse Luna. It seems that theres is a date issue with tortoiseSVN within the add-on. Take a look at the resuming prompt
![Screenshot](https://cloud.githubusercontent.com/assets/10478999/11334709/245abe5e-91d7-11e5-9193-19936e1d25d7.png)

**Comment by SBM1952** [comment]
Hi, My error was copying locally into EclipseWorkspace,
When i don't copy it into workspace, the addon works aswell on Luna and Mars.

Thanks in advance, great add-on!

**Comment by ContextQuickie** [comment]
Ok, I close the issue
