### ISSUE TITLE
Used Eclipse versions

### ISSUE THREAD

**Issue by ContextQuickie** [ContextQuickie/ContextQuickie#20]
I want to use this issue as a kind of survey to check which Eclipse versions are used with ContextQuickie. Two years ago, issue #6 has been created to support Java 1.6 with Eclipse Kepler. Are there still users who use Eclipse Kepler? You can add a thumbs up to the comments below if you are using the mentioned version.

**Comment by ContextQuickie** [comment]
Eclipse Kepler users

**Comment by ContextQuickie** [comment]
Eclipse Luna users

**Comment by ContextQuickie** [comment]
Eclipse Mars users

**Comment by ContextQuickie** [comment]
Eclipse Neon users

**Comment by ContextQuickie** [comment]
Eclipse Oxygen users

**Comment by ContextQuickie** [comment]
Eclipse Photon users

**Comment by gabsoftware** [comment]
Eclipse Indigo here (3.7.x). It worked before with 0.8 but not working anymore with 0.9.

**Comment by ContextQuickie** [comment]
Hello @gabsoftware ,
yes, support for older eclipse versions was removed in version 0.9. Do you miss any features in 0.8 or can you work with it?

**Comment by gabsoftware** [comment]
I tried to update to 0.9 because even if I disabled TortoiseSVN menus, ContextQuickie still shows all the menu entries. That's annoying.

**Comment by ContextQuickie** [comment]
Hello @gabsoftware ,
is it working better with version 0.8.6 from the development update site (http://contextquickie.github.io/ContextQuickie/Development)?
In my indigo workspace, I hat to enable and disable TortoiseSVN to get it working, not sure if it is required in your installation.
