### ISSUE TITLE
Version 0.9: Beyond compare entry disappeared on popup menu of XML file editor

### ISSUE THREAD

**Issue by toutzhang** [ContextQuickie/ContextQuickie#21]
Beyond compare entry disappeared on popup menu of XML file editor.
![popup](https://user-images.githubusercontent.com/40381675/44318343-f8597880-a467-11e8-99a5-836d699b26be.png)

Popup menu on "Package Explorer" view is okay.
Eclipse Photon

**Comment by ContextQuickie** [comment]
Hello @toutzhang,
I fixed the issue but I'm currently working on some other topics which will delay a new release. Currently I plan a new release beginning of next week. Do you already need a test version? This would be completely untested with a lot of changes :-(

**Comment by toutzhang** [comment]
That's okay, prepare new release at your own pace.
Current release works fine and that issue can also work around.

**Comment by ContextQuickie** [comment]
Hello @toutzhang,
this issue should be fixed with version 0.9.1

**Comment by toutzhang** [comment]
> Hello @toutzhang,
> this issue should be fixed with version 0.9.1

Good job, thanks.
