### ISSUE TITLE
add tortoisegit languagepack support

### ISSUE THREAD

**Issue by pbl-pw** [ContextQuickie/ContextQuickie#23]
eclipse tortoisegit context menu only display English, not tortoisegit setting languagepack

**Comment by ContextQuickie** [comment]
Hello @pbl-pw ,
are you interested in a specific language?

**Comment by pbl-pw** [comment]
@ContextQuickie : Chinese

**Comment by ContextQuickie** [comment]
Hello @pbl-pw , 
there are two Chinese translations for Tortoise Git: Traditional and simplified. Which one do you need?

**Comment by pbl-pw** [comment]
![contextquickie](https://user-images.githubusercontent.com/3636470/45864904-3f5fc400-bdae-11e8-8dc7-5f05b545547e.jpg)
It's working as expected now. Thank you!

**Comment by ContextQuickie** [comment]
Translation support is now included in version 0.9.2
