### ISSUE TITLE
Tortoise Git version list missing 2.8

### ISSUE THREAD

**Issue by toutzhang** [ContextQuickie/ContextQuickie#26]
**Describe the bug**
I've installed Tortoise Git 2.8.0.0. But this place doesn't include this version:
![image](https://user-images.githubusercontent.com/40381675/57833681-28625c00-77ed-11e9-890d-8f75c0385d1c.png)

**To Reproduce**
Window > Preferences > Context Quickie > Select Tortoise Git version

**Desktop (please complete the following information):**
 - Eclipse version 4.11.0
 - Java runtime ( 64bit)
 - ContextQuickie version [0.12.0.201905101506]

**Used ContextQuickie features:**
 - Beyond Compare
 - Tortoise Git

**Comment by ContextQuickie** [comment]
Hello @toutzhang ,
you can still use the settings for version 2.7. There hasn't been changes in the menu between version 2.7 and 2.8. There will be a change in the next version where this configruation item is remvoed and the current version will be read directly from the registry.
BR
Roland

**Comment by ContextQuickie** [comment]
Added selection for Tortoise Git 2.8 and 2.8 in version 0.13
