### ISSUE TITLE
Popup menu item spelling mistake

### ISSUE THREAD

**Issue by toutzhang** [ContextQuickie/ContextQuickie#28]
**Describe the bug**
Tortoise Git in Eclipse popup menu has a spelling mistake: Tort**io**seGit

**Screenshots**
![git](https://user-images.githubusercontent.com/40381675/88382623-6ab4ff00-cddb-11ea-9bef-a0f984bb6f33.png)

**Desktop (please complete the following information):**
 - Eclipse version: 4.16
 - ContextQuickie version: 0.14.0

**Used ContextQuickie features:**
 - Beyond Compare
 - Tortoise Git

**Comment by ContextQuickie** [comment]
Hello @toutzhang,
thanks for the information. I fixed the typo in version 0.14.1.
Best Regards
Roland
