### ISSUE TITLE
Productize TortoiseHg support

### ISSUE THREAD

**Issue by dpeger** [ContextQuickie/ContextQuickie#31]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when using the MercurialEclipse Plugin. This plugin is so slow (I'm working an a laaarge repo) that basically all SCM related actions are executed in TortoiseHg.

**Describe the solution you'd like**
I'd like to have a basic integration of TortoiseHg into Eclipse. A TeamProivder would be nice but basically I only need to call "annotate" and "vdiff"

**Describe alternatives you've considered**
Currently I configured some basic commands using EasyShell.

**Additional context**
I browsed your source code a little and found some TortoiseHg related classes. Without any knowledge about this project I'm wondering what it would take to offer some basic Hg-Support. Maybe I could offer some time to help!?

**Comment by ContextQuickie** [comment]
Hello @dpeger ,
yes, there was initially a plan to support Tortoise Hg but never continued because the interface to Tortoise Hg differs extremely from Git/SVN as far as I remember. Additionally, I don't have any experience with Tortoise Hg.
But I can have another look at it. Which Toritoise Hg version are you using?
If you have time left maybe you can support me either with development or testing of Tortoise Hg.
BR
Roland

**Comment by dpeger** [comment]
As you were asking I updated to the most recent version of TortoiseHg (5.5rc2). Before I was using 3.7.2 (I can't even find a download for this anymore).

Testing TortoiseHg integration would be a pleasure!!

**Comment by ContextQuickie** [comment]
Hello @dpeger,
the first version with Tortoise Hg support is available at the development update site: http://contextquickie.github.io/ContextQuickie/Development
If I didn't miss anything, basic support for Tortoise Hg should work. Can you please have a look at it?
Limitations:
- Menu is only shown if one file or folder is selected. Selecting multiple files/folders is not (yet) supported
- The icons don't look perfect at the moment
- No translation support, only english
- All menu items are shown in the sub menu, settings are not yet considered
- All menu items are shown independend of the the current context
BR
Roland

**Comment by dpeger** [comment]
Thanks for the quick support. I just installed the extension.

As you mentioned the extension is currently showing the TortoiseHg menu items without considering the context. That is always the (lets call it) global items are shown. But the items available seem to work without issues.

**TortoiseHg context menu in cloned working copy without any selection**
![2020-08-10_09h56_47](https://user-images.githubusercontent.com/8697665/89762412-ad234f00-daf0-11ea-9035-b9ca356d6c1e.png)

**TortoiseHg context menu in cloned working copy with a file/folder selection**
![2020-08-10_09h58_29](https://user-images.githubusercontent.com/8697665/89762461-c7f5c380-daf0-11ea-943a-e2c2b45377b6.png)

**Comment by ContextQuickie** [comment]
Hello @dpeger ,
I pushed a new version to the development update site, can you please have a look at it?
The visibility changes are updated now, please tell me if there is something wrong or missing.
And I updated some icons.
BR
Roland

**Comment by dpeger** [comment]
Icon looking are fine now. And the menu items seem to be correctly read from the configuration.

The only thing I'm missing right now would be file context to have file/folder specific actions.

**Comment by ContextQuickie** [comment]
Hello @dpeger ,
I pushed a new version to the development update site with basic support for showing entries based on the file/folder selection.
Can you please have a look at it? Please tell me if there is something wrong or missing.
BR
Roland

**Comment by dpeger** [comment]
I updated to 0.15.0.202008102013 but the menu is still always the global TotoiseHg menu:

![image](https://user-images.githubusercontent.com/8697665/89876465-fa6df200-dbbe-11ea-8fa6-2b7a15d618d0.png)


Additionally I noticed the TotoiseHg context menu is also shown on projects that are not under SCM despite the "Show TortoiseHg only if a working copy has been found" setting being checked

![image](https://user-images.githubusercontent.com/8697665/89876589-28ebcd00-dbbf-11ea-930d-df3a7d4b6423.png)

**Comment by ContextQuickie** [comment]
Hello @dpeger ,
that's strange. I installed the latest version and I see the whole menu only if a working copy was found:
![image](https://user-images.githubusercontent.com/15061118/89929483-87d63400-dc09-11ea-8236-cfd5f40380f6.png)

If no working copy has been found I see only the the default entries:
![image](https://user-images.githubusercontent.com/15061118/89929595-b227f180-dc09-11ea-9473-7d1202029176.png)

Can you please try it again with a clean eclipse installation or check if there are still artifacts from the previous version in your eclipse folder?

BR
Roland

**Comment by dpeger** [comment]
Yes you're right of course. Without a working copy there are different menu items. But I actually expected the whole TortoiseHg menu to be hidden if a project is not under SCM and the "Show TortoiseHg only if a working copy has been found" setting is enabled.

**Comment by ContextQuickie** [comment]
Hello @dpeger ,
yes, the option is probably a little bit misleading. The intended behavoir is to show context menu entries identical to the windows explorer. "Show working copy elements only if working copy has been found" would be the better description for this option.
Do you need a option to hide Tortoise Hg completely if no working copy is present?

BR
Roland

**Comment by dpeger** [comment]
Thanks for your time so far!

No that's not something I need.

The only thing that I'm missing are the context-aware actions. That is the actions that work on files or directories of a working copy. For example annotate, history, ...

**Comment by ContextQuickie** [comment]
Hello @dpeger ,
I tried to add "Annotate Files" and "Revision History". Can you please check if it works as expected?
BR
Roland

**Comment by dpeger** [comment]
Looks pretty good. I'll ask some other colleagues to test as well, but I saw no problems so far...

**Comment by dpeger** [comment]
I noticed that in Eclipse other/more options are shown in the context menu compared to the explorer context menu on the same file.

Windows Explorer Context Menu
![Windows Explorer Context Menu](https://user-images.githubusercontent.com/8697665/92003869-cc08b000-ed41-11ea-8f78-b9083ac14ef0.png)

Eclipse Context Quickie Context Menu
![Eclipse Context Quickie Context Menu](https://user-images.githubusercontent.com/8697665/92003878-cdd27380-ed41-11ea-92b3-4602fbb049c5.png)

**Comment by ContextQuickie** [comment]
Hello @dpeger ,
I changed the visibility setting for some entries. The new version is available on the development update site.
BR
Roland

**Comment by dpeger** [comment]
I tried to update the plugin but got this exception:

```
An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: http://contextquickie.github.io/ContextQuickie/Development/plugins/ContextQuickie_0.15.0.202009051238.jar.
http://contextquickie.github.io/ContextQuickie/Development/plugins/ContextQuickie_0.15.0.202009051238.jar
Artifact not found: http://contextquickie.github.io/ContextQuickie/Development/plugins/ContextQuickie.Windows_0.1.1.202009051238.jar.
http://contextquickie.github.io/ContextQuickie/Development/plugins/ContextQuickie.Windows_0.1.1.202009051238.jar
Artifact not found: http://contextquickie.github.io/ContextQuickie/Development/features/ContextQuickie_0.15.0.202009051238.jar.
http://contextquickie.github.io/ContextQuickie/Development/features/ContextQuickie_0.15.0.202009051238.jar
```

**Comment by ContextQuickie** [comment]
Hello @dpeger,
you're right, I forgot to commit some files. Should be fixed now.
BR
Roland

**Comment by dpeger** [comment]
Looks good now. Thanks

**Comment by dpeger** [comment]
Everything seems to be working so far. Thanks for the quick support!

**Comment by dpeger** [comment]
@ContextQuickie as the integration seems to work nicely, are you going to publish this officially? The market place still advertises release 0.14.2.

**Comment by ContextQuickie** [comment]
Hello @dpeger ,
0.15.0 is released now.
BR
Roland
