### ISSUE TITLE
Difference between ContextQuickie and ContextQuickie2?

### ISSUE THREAD

**Issue by DonaldJLucas** [ContextQuickie/ContextQuickie#35]
What is the difference between ContextQuickie and ContextQuickie2?  Which should I be using?  Or both?  I'm confused.
Thanks for your help and a really great application!

Don Lucas

**Comment by ContextQuickie** [comment]
Hello @DonaldJLucas ,
ContextQuickie is currently the preferred solution, but it supports only Tortoise Hg/Git/SVN and Beyond Compare.
ContextQuickie2 is currently under development and will support more context menu extensions (e.g. Notepad++).
Theoretically it should be possible to get ContextQuickie behavoir also in ContextQuickie2, but as already mentioned it's still under development. So maybe it still contains some "hidden features" :-)
Does this answer your question?
BR
Roland

**Comment by DonaldJLucas** [comment]
Thanks for the very quick answer, Roland!  That is what I am looking for...  I was preparing a new laptop for our build environment for another engineer and noticed that there were now two ContextQuickies, and so I wasn't sure which to load.  I actually loaded both just to see what the 2nd one looked like, but I will uninstall it until it reaches a more stable level.  I take it that ContextQuickie2 no longer requires the detailed setup information (such as for BeyondCompare)?  Nice!  And by the way, I love BeyondCompare and Notepad++ so I look forward to ContextQuickie2 becoming closer to its final form (and is software ever in its "final" form?).

Thanks again for a great application!

Don

**Comment by ContextQuickie** [comment]
Hello @DonaldJLucas ,
right, ContextQuickie2 don't require the configuration of the tools anymore because it uses directly the context menu provided by the system (close to the one you see in the Explorer).
BR
Roland
