### ISSUE TITLE
Tortoise SVN menu is not displayed on a source folder

### ISSUE THREAD

**Issue by aalejo** [ContextQuickie/ContextQuickie#5]
I do not know if it's a issue or a feature request.

Tested with Eclipse Mars on Windows 7

**Comment by ContextQuickie** [comment]
Do you have any further information regarding this topic:
- Which version of ContextQuickie are you using?
- Which project type is affected?
- Which ContextQuickie settings do you use?

**Comment by aalejo** [comment]
Version:   ContextQuickie	0.4.1.201511210944
Project type: Dynamic Web Project
Settings:
![settings](https://cloud.githubusercontent.com/assets/17143165/13046148/7a798e72-d3d7-11e5-9de8-2f4b43389063.png)

The Tortoise menu is not displayed when you click on a file or folder inside the Java source code:
![context_menu](https://cloud.githubusercontent.com/assets/17143165/13046423/0ea5f2ec-d3d9-11e5-8c1d-3635bbb4d2eb.png)

However the menu is displayed when it comes to a directory or file outside the source code:
![context_menu_2](https://cloud.githubusercontent.com/assets/17143165/13046522/9110e5f2-d3d9-11e5-8339-a00ab4018abc.png)

Regards.

**Comment by ContextQuickie** [comment]
I tried to fix the problem in version 0.5.0. Can you please have a look at it?

**Comment by aalejo** [comment]
The problem has been fixed!!

Thank you very much
