### ISSUE TITLE
Plugin doesn't support Java 1.6 and Eclipse Kepler

### ISSUE THREAD

**Issue by whitchcock** [ContextQuickie/ContextQuickie#6]
I am currently stuck using Java 1.6 with Eclipse Kepler. Due to setting requiring 1.7 I was unable to use the plugin. The ContextQuickie preference options were not available to me.

I was able to rebuild the jar locally with settings to allow support of JavaSE-1.6. After installing my custom jar the plugin worked as expected and really liked the ability to easily access to TortoiseSVN and Beyond Compare.

**Comment by ContextQuickie** [comment]
Added support for java 1.6 in release 0.5.1

**Comment by whitchcock** [comment]
Update works as expected. Thanks for the quick fix.
