### ISSUE TITLE
Context menu is visible only in Project Explorer view

### ISSUE THREAD

**Issue by lalitchattar** [ContextQuickie/ContextQuickie#7]
I installed this plugin ad working fine but the context menu is visible only in project explorer view. If i open my project in navigator view or if right click on open file in editor, menu is not coming.

**Comment by ContextQuickie** [comment]
Hello lalitchattar,
can you please provide screenshots showing the menus in which you expect ContextQuickie to appear? Furthermore, the following information would be helpful:
- Which eclipse version do you use?
- Which project type is affected?

**Comment by lalitchattar** [comment]
Thank you for your reply.  

![screen_one](https://cloud.githubusercontent.com/assets/19869031/15983815/17ef82f6-2fd1-11e6-8927-9e1b15d55dc4.png)

Ok. So this is screen one which shows SVN menus. But in Next image which is of Navigator view

![screen_two](https://cloud.githubusercontent.com/assets/19869031/15983823/3d15c018-2fd1-11e6-8905-67355c2df008.png)

is not showing menu. Same is happening when I right click on file in editor. See Image three below.

![screen_three](https://cloud.githubusercontent.com/assets/19869031/15983829/63a535d8-2fd1-11e6-9d40-9502deda5ba3.png)


I tried it with bot java and Maven web project.

**Comment by ContextQuickie** [comment]
Attached you will find an updated version of ContextQuickie supporting more context menus. Unfortunately the position in the menu had to be changed to get it working. There also are still some issues with some editors. C/C++/Java editors seem to work, the eclipse XML editor not.
Can you please have a look at it? For installation, you have to unpack it and set the unpacked directory  as Update Site location.

There will be a release in the next day if I fixed the problems with the editors and the made changes cause no other problems.

[ContextQuickie_UpdateSite.zip](https://github.com/ContextQuickie/ContextQuickie/files/310214/ContextQuickie_UpdateSite.zip)

**Comment by lalitchattar** [comment]
Thank you for your quick reply. It is working fine. I tested it with XML editor in eclipse Luna and it is working. Might be I could not understand your "XML editor" meaning.

![screen_four](https://cloud.githubusercontent.com/assets/19869031/15984945/e03b6f2c-2ff9-11e6-8f1d-0ee8b2b7bbb5.png)

**Comment by lalitchattar** [comment]
It will be better if you add Tortoise icons on files when we make any changes. Currently I am having Subversion plugin installed in my eclipse so whenever I make any changes it shows Subversion icon and change icon when I commit file. But for this it update svn cache. For small project it is fast but for big project updating svn cache cost performance issue in eclipse. some times hangs.

Well you have done great job. Thank you

**Comment by ContextQuickie** [comment]
I changed the code which fixes some issues with the current implementation regarding this topic. The release can be downloaded via the default update site

Regarding the comment with the icons:
Currently there are no plans to support such a feature. ContextQuickie is intended to extend the context menu, not the displayed files/folders. In my opinion it is a lot of effort to implement the requested feautre and requires additional APIs for retrieving the current SVN state of a file system object (e.g. using the SVN command or using a SVN APIs provided by the eclipse framework). This would cause additional dependencies to ContextQuickie which a want to avoid.

If you don't have any comments regarding this topic, you can close this issue.

**Comment by lalitchattar** [comment]
The problem has been fixed!!

Thank you very much
