### ISSUE TITLE
Tortoise SVN Diff on two files in package explorer

### ISSUE THREAD

**Issue by bc15** [ContextQuickie/ContextQuickie#9]
When I select two files (with Ctrl key) in package explorer, and then select Tortoise SVN -> Diff over ContextQuickie, it would be nice to actually see the difference between the two files.
Currently it doesn't work, only one file is selected for Diff.

**Comment by ContextQuickie** [comment]
I tried to fix this issue in version 0.6.2. Can you please have a look at it?
If you don't have any comments regarding this topic, you can close this issue.

**Comment by bc15** [comment]
Yes, it works now.
Thank you, and keep up the good work!
